/// @file
///
/// @author
///
/// @copyright

#ifndef MORSECODETRANSLATORENGINE_GLOBAL_H
#define MORSECODETRANSLATORENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MORSECODETRANSLATORENGINE_LIBRARY)
#define MORSECODETRANSLATORENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#define MORSECODETRANSLATORENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MORSECODETRANSLATORENGINE_GLOBAL_H
